package org.abhi.synapse.metrics;


import java.util.ArrayList;
import java.util.List;

/**
 * In-memory metrics storage for Synapse HTTP requests.
 *
 * <p>Aggregates request-level metrics including latency, token usage, and success/failure
 * counts. Each request is recorded via {@link #recordRequest} and stored both as aggregated
 * counters and as individual {@link RequestMetric} entries for detailed analysis.</p>
 *
 * <p>Thread-safety: this class is <em>not</em> thread-safe. Callers must synchronize access
 * if multiple threads record metrics concurrently.</p>
 *
 * @author Abhiram Rathod
 * @since 1.0.0
 * @see RequestMetric
 * @see SynapseMetricsCollector
 */
public class SynapseMetrics {

    private long totalRequests;
    private long successfulRequests;
    private long failedRequests;
    private long totalPromptTokens;
    private long totalCompletionTokens;
    private long totalLatencyMs;
    private final List<RequestMetric> requestMetrics = new ArrayList<>();

    /**
     * Records a single HTTP request's metrics.
     *
     * <p>Increments aggregate counters (total, success/failure, token counts, latency)
     * and appends a new {@link RequestMetric} entry to the internal list.</p>
     *
     * @param model           the model name used for the request (e.g. {@code "gpt-4"})
     * @param latencyMs       the round-trip latency of the request in milliseconds
     * @param promptTokens    the number of prompt tokens consumed by the request
     * @param completionTokens the number of completion tokens generated by the request
     * @param success {@code true} if the request completed successfully, {@code false} otherwise
     * @since 1.0.0
     */
    public void recordRequest(String model, long latencyMs, int promptTokens,
                              int completionTokens, boolean success) {
        totalRequests++;
        if (success) {
            successfulRequests++;
        } else {
            failedRequests++;
        }
        totalPromptTokens += promptTokens;
        totalCompletionTokens += completionTokens;
        totalLatencyMs += latencyMs;
        requestMetrics.add(new RequestMetric(model, latencyMs, promptTokens,
                completionTokens, success));
    }

    /**
     * Returns the total number of recorded requests (both successful and failed).
     *
     * @return the cumulative request count
     * @since 1.0.0
     */
    public long getTotalRequests() {
        return totalRequests;
    }

    /**
     * Returns the total number of successfully completed requests.
     *
     * @return the cumulative successful request count
     * @since 1.0.0
     */
    public long getSuccessfulRequests() {
        return successfulRequests;
    }

    /**
     * Returns the total number of failed requests.
     *
     * @return the cumulative failed request count
     * @since 1.0.0
     */
    public long getFailedRequests() {
        return failedRequests;
    }

    /**
     * Returns the total number of prompt tokens consumed across all recorded requests.
     *
     * @return the cumulative prompt token count
     * @since 1.0.0
     */
    public long getTotalPromptTokens() {
        return totalPromptTokens;
    }

    /**
     * Returns the total number of completion tokens generated across all recorded requests.
     *
     * @return the cumulative completion token count
     * @since 1.0.0
     */
    public long getTotalCompletionTokens() {
        return totalCompletionTokens;
    }

    /**
     * Returns the combined total of prompt and completion tokens across all recorded requests.
     *
     * @return the cumulative total token count (prompt + completion)
     * @since 1.0.0
     */
    public long getTotalTokens() {
        return totalPromptTokens + totalCompletionTokens;
    }

    /**
     * Returns the cumulative latency in milliseconds across all recorded requests.
     *
     * @return the total latency in milliseconds
     * @since 1.0.0
     */
    public long getTotalLatencyMs() {
        return totalLatencyMs;
    }

    /**
     * Calculates the average latency in milliseconds across all recorded requests.
     *
     * @return the average latency in milliseconds, or {@code 0.0} if no requests have been recorded
     * @since 1.0.0
     */
    public double getAverageLatencyMs() {
        if (totalRequests == 0) return 0;
        return (double) totalLatencyMs / totalRequests;
    }

    /**
     * Calculates the success rate as a percentage of total recorded requests.
     *
     * @return the success rate as a percentage (0.0 - 100.0), or {@code 0.0} if no requests have been recorded
     * @since 1.0.0
     */
    public double getSuccessRate() {
        if (totalRequests == 0) return 0;
        return (double) successfulRequests / totalRequests * 100;
    }

    /**
     * Returns an unmodifiable snapshot of all individual request metrics.
     *
     * @return a copy of the internal {@link RequestMetric} list (unmodifiable)
     * @since 1.0.0
     */
    public List<RequestMetric> getRequestMetrics() {
        return List.copyOf(requestMetrics);
    }

    /**
     * Resets all recorded metrics to their initial state.
     *
     * <p>Clears all aggregate counters and removes all stored {@link RequestMetric} entries.</p>
     *
     * @since 1.0.0
     */
    public void reset() {
        totalRequests = 0;
        successfulRequests = 0;
        failedRequests = 0;
        totalPromptTokens = 0;
        totalCompletionTokens = 0;
        totalLatencyMs = 0;
        requestMetrics.clear();
    }

    /**
     * Immutable data class representing metrics for a single HTTP request to Synapse.
     *
     * <p>Captures the model name, round-trip latency, token consumption breakdown,
     * and success/failure status of an individual request.</p>
     *
     * @author Abhiram Rathod
     * @since 1.0.0
     * @see SynapseMetrics
     */
    public static class RequestMetric {
        private final String model;
        private final long latencyMs;
        private final int promptTokens;
        private final int completionTokens;
        private final boolean success;

        /**
         * Constructs a new {@code RequestMetric} with the specified details.
         *
         * @param model            the model name used for the request
         * @param latencyMs        the round-trip latency in milliseconds
         * @param promptTokens     the number of prompt tokens consumed
         * @param completionTokens the number of completion tokens generated
         * @param success          {@code true} if the request succeeded, {@code false} otherwise
         * @since 1.0.0
         */
        public RequestMetric(String model, long latencyMs, int promptTokens,
                             int completionTokens, boolean success) {
            this.model = model;
            this.latencyMs = latencyMs;
            this.promptTokens = promptTokens;
            this.completionTokens = completionTokens;
            this.success = success;
        }

        /**
         * Returns the model name used for this request.
         *
         * @return the model name (e.g. {@code "gpt-4"})
         * @since 1.0.0
         */
        public String getModel() {
            return model;
        }

        /**
         * Returns the round-trip latency of this request in milliseconds.
         *
         * @return the latency in milliseconds
         * @since 1.0.0
         */
        public long getLatencyMs() {
            return latencyMs;
        }

        /**
         * Returns the number of prompt tokens consumed by this request.
         *
         * @return the prompt token count
         * @since 1.0.0
         */
        public int getPromptTokens() {
            return promptTokens;
        }

        /**
         * Returns the number of completion tokens generated by this request.
         *
         * @return the completion token count
         * @since 1.0.0
         */
        public int getCompletionTokens() {
            return completionTokens;
        }

        /**
         * Indicates whether this request completed successfully.
         *
         * @return {@code true} if the request succeeded, {@code false} otherwise
         * @since 1.0.0
         */
        public boolean isSuccess() {
            return success;
        }
    }
}
