<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.abhi</groupId>
		<artifactId>synapse-parent</artifactId>
		<version>0.0.1-SNAPSHOT</version>
	</parent>

	<artifactId>synapse-http</artifactId>
	<name>Synapse HTTP</name>

	<properties>
		<automatic.module.name>org.abhi.synapse.http</automatic.module.name>
	</properties>
	<description>HTTP implementation</description>

	<dependencies>
		<dependency>
			<groupId>org.abhi</groupId>
			<artifactId>synapse-core</artifactId>
		</dependency>
		<dependency>
			<groupId>org.abhi</groupId>
			<artifactId>synapse-interceptors</artifactId>
		</dependency>
		<dependency>
			<groupId>org.abhi</groupId>
			<artifactId>synapse-config</artifactId>
		</dependency>
		<dependency>
			<groupId>org.abhi</groupId>
			<artifactId>synapse-metrics</artifactId>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
		</dependency>
		<dependency>
			<groupId>com.squareup.okhttp3</groupId>
			<artifactId>mockwebserver</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.assertj</groupId>
			<artifactId>assertj-core</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

</project>
